AWSTemplateFormatVersion: "2010-09-09"
Description: Groups and Meetings User Pool
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The environment to deploy the stack to
  CallBackURL:
    Type: String
    Default: https://localhost:3000/login
    Description: The URL to redirect to after login
  LogoutURL:
    Type: String
    Default: https://localhost:3000/logout
    Description: The URL to redirect to after logout  
Resources:
  GroupsAndMeetingsUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: GroupsAndMeetingsUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: phoneNumber
          AttributeDataType: String
          Mutable: true
          Required: false
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  GroupsAndMeetingsUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: groupsandmeetinsapp
      UserPoolId:
        Ref: GroupsAndMeetingsUserPool

  GroupsAndMeetingsUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: GroupsAndMeetingsUserPoolClient
      UserPoolId:
        Ref: GroupsAndMeetingsUserPool
      GenerateSecret: true
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      ExplicitAuthFlows: 
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO   
      TokenValidityUnits:
         AccessToken: minutes
         IdToken: minutes
         RefreshToken: days
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 10
      EnableTokenRevocation: true
      CallbackURLs:
        - Ref: CallBackURL
      LogoutURLs:
        - Ref: LogoutURL