
services:
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    name: mysql-data